name: Deploy to Production (Frontend)

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Environment Variables
        run: |
          echo "NEXT_PUBLIC_SERVER_URL=$SERVER_URL" >> .env.production
          echo "NEXT_PUBLIC_GH_ID=$GH_ID" >> .env.production
          echo "NEXT_PUBLIC_GH_CALLBACK=$GH_CALLBACK" >> .env.production
        env:
          CI: false
          SERVER_URL: '${{ secrets.SERVER_URL }}'
          GH_ID: '${{ secrets.GH_ID }}'
          GH_CALLBACK: '${{ secrets.GH_CALLBACK }}'

      - name: Transfer Environment Variables with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: '.env.production'
          target: 'knoticle/frontend'

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: ${{ secrets.SSH_FRONTEND_SCRIPT }}
